---
- name: installing some packages
  apt:
    pkg={{ item }}
    state=present
  with_items:
    - dnsmasq
  tags:
    - install

- name: enable ipv4 forward
  lineinfile:
    dest=/etc/sysctl.conf
    regexp='^net.ipv4.ip_forward=1$'
    state=present
    line='net.ipv4.ip_forward=1'
    insertafter=EOF
  tags:
    - conf

- name: network nat rules configuration
  template:
    src=etc_iptables.ipv4.nat.j2
    dest=/etc/iptables.ipv4.nat
    mode=0644
    owner=root
    group=root
  tags:
    - conf

- name: dnsmasq configuration
  template:
    src=etc_dnsmasq.conf.j2
    dest=/etc/dnsmasq.conf
    mode=0644
    owner=root
    group=root
  notify: restart dnsmasq
  tags:
    - conf

- name: system services
  service:
    name={{ item }}
    state=started
    enabled=yes
  with_items:
    - dnsmasq
  tags:
    - conf

